package services

import (
	"database/sql"
	"fmt"
	"io"
	"time"
)

// PgDumpOptions controls what gets included in the dump output
type PgDumpOptions struct {
	Schemas       []string // nil/empty = all non-system schemas
	ExcludeTables []string
	NoOwner       bool
	Clean         bool // DROP IF EXISTS before CREATE
}

// PgDumpService performs a pure Go PostgreSQL database dump
type PgDumpService struct {
	db      *sql.DB
	options PgDumpOptions
	writer  io.Writer
}

// NewPgDumpService creates a new dump service
func NewPgDumpService(db *sql.DB, options PgDumpOptions, writer io.Writer) *PgDumpService {
	return &PgDumpService{
		db:      db,
		options: options,
		writer:  writer,
	}
}

// Dump performs the full database dump
func (s *PgDumpService) Dump() error {
	if err := s.writeHeader(); err != nil {
		return fmt.Errorf("writing header: %w", err)
	}

	// Pre-data: extensions, schemas, types, sequences, tables, views, functions
	if err := s.dumpExtensions(); err != nil {
		return fmt.Errorf("dumping extensions: %w", err)
	}
	if err := s.dumpSchemas(); err != nil {
		return fmt.Errorf("dumping schemas: %w", err)
	}
	if err := s.dumpEnumTypes(); err != nil {
		return fmt.Errorf("dumping enum types: %w", err)
	}
	if err := s.dumpSequences(); err != nil {
		return fmt.Errorf("dumping sequences: %w", err)
	}
	if err := s.dumpTables(); err != nil {
		return fmt.Errorf("dumping tables: %w", err)
	}
	if err := s.dumpViews(); err != nil {
		return fmt.Errorf("dumping views: %w", err)
	}
	if err := s.dumpFunctions(); err != nil {
		return fmt.Errorf("dumping functions: %w", err)
	}

	// Data
	if err := s.dumpAllTableData(); err != nil {
		return fmt.Errorf("dumping table data: %w", err)
	}

	// Post-data: indexes, foreign keys, triggers
	if err := s.dumpIndexes(); err != nil {
		return fmt.Errorf("dumping indexes: %w", err)
	}
	if err := s.dumpForeignKeys(); err != nil {
		return fmt.Errorf("dumping foreign keys: %w", err)
	}
	if err := s.dumpTriggers(); err != nil {
		return fmt.Errorf("dumping triggers: %w", err)
	}

	if err := s.writeFooter(); err != nil {
		return fmt.Errorf("writing footer: %w", err)
	}

	return nil
}

func (s *PgDumpService) writeHeader() error {
	header := fmt.Sprintf(`--
-- PostgreSQL database dump
-- Generated by sql-toolbox backup (pure Go)
-- Timestamp: %s
--

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

`, time.Now().UTC().Format(time.RFC3339))
	_, err := fmt.Fprint(s.writer, header)
	return err
}

func (s *PgDumpService) writeFooter() error {
	_, err := fmt.Fprint(s.writer, "\n--\n-- PostgreSQL database dump complete\n--\n")
	return err
}

func (s *PgDumpService) writef(format string, args ...interface{}) error {
	_, err := fmt.Fprintf(s.writer, format, args...)
	return err
}

func (s *PgDumpService) writeln(line string) error {
	_, err := fmt.Fprintln(s.writer, line)
	return err
}

// isSchemaIncluded checks whether a schema should be included in the dump
func (s *PgDumpService) isSchemaIncluded(schema string) bool {
	if len(s.options.Schemas) == 0 {
		return true
	}
	for _, sch := range s.options.Schemas {
		if sch == schema {
			return true
		}
	}
	return false
}

// isTableExcluded checks whether a table should be excluded from the dump
func (s *PgDumpService) isTableExcluded(table string) bool {
	for _, t := range s.options.ExcludeTables {
		if t == table {
			return true
		}
	}
	return false
}

// qualifiedName returns schema.name, quoting identifiers
func qualifiedName(schema, name string) string {
	return fmt.Sprintf("%s.%s", quoteIdentifier(schema), quoteIdentifier(name))
}

// quoteIdentifier quotes a PostgreSQL identifier
func quoteIdentifier(name string) string {
	return `"` + name + `"`
}
