<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- <PublishAot>true</PublishAot>
    <PublishTrimmed>true</PublishTrimmed> -->
    <RootNamespace>SqlMigration</RootNamespace>
    <AssemblyName>sql-migration</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Npgsql" Version="9.0.3" />
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta5.25306.1" />
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
  </ItemGroup>

</Project>
